$(function(){
	//--
	$('.indexPart3').find('li:last').css('border','0px');
	$('.Application2').find('.listDiv').find('li:last').css('border','0px');
	$('.ApplicationRank').find('li:last').css('border','0px');
	$('.ApplicationShowPart3').find('li:even').css('background','#f3f3f3');
	$('.mediaCenter').find('li:last').css('border','0px');
	//--首页焦点图
	var fadeFlashTime=new Array();
	$('.fadeFlash').find('li:first').fadeIn(500);
	$('.fadeFlash').each(function(i){
		fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
		$(this).find('.btnDiv').find('span').each(function(ii){
			$(this).hover(
			function(){
				clearInterval(fadeFlashTime[i]);
				$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
				$(this).addClass('spanNow');
				$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
				fadeFlashNow[i]=ii;
				$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
				fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
				},
			function(){}	
				)
			})
		$(this).find('.rightBtn').click(function(){
			clearInterval(fadeFlashTime[i]);
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
			if(fadeFlashNow[i]<$('.fadeFlash').eq(i).find('li').length-1){
				fadeFlashNow[i]++;
				}else{
					fadeFlashNow[i]=0;
					}
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').eq(fadeFlashNow[i]).addClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
			fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
			})	
		$(this).find('.leftBtn').click(function(){
			clearInterval(fadeFlashTime[i]);
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
			if(fadeFlashNow[i]>0){
				fadeFlashNow[i]--;
				}else{
					fadeFlashNow[i]=$('.fadeFlash').eq(i).find('li').length-1;
					}
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').eq(fadeFlashNow[i]).addClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
			fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
			})	
		})
	//--栏目页焦点图	
	//--选项卡
	$('.tabContentDiv').find('.tabContent:first').show();
	$('.tab').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).hover(
			function(){
				$('.tab').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.tabContentDiv').eq(i).find('.tabContent').hide();
				$('.tabContentDiv').eq(i).find('.tabContent').eq(ii).show();
				},
			function(){}	
				)
			})
		})
	//--精品推荐
	$('.ApplicationPart1').find('li').hover(
	    function(){
			$(this).addClass('liNow');
			},
		function(){
			$(this).removeClass('liNow');
			}
	)	
	//--
	$('.ApplicationShowPart2').find('.rightBtn').click(function(){
		imgScrollRight2($('.ApplicationShowPart2').find('.list'),$('.ApplicationShowPart2').find('li').length/2-1,530,0);
		})	
	$('.ApplicationShowPart2').find('.leftBtn').click(function(){
		imgScrollLeft2($('.ApplicationShowPart2').find('.list'),$('.ApplicationShowPart2').find('li').length/2-1,530,0);
		})	
	//--案例
	$('.case').find('.contentDiv:first').show();
	$('.case').find('.rightBtn').click(function(){
		imgScrollRight2($('.case').find('.list'),$('.case').find('li').length-1,135,0);
		})	
	$('.case').find('.leftBtn').click(function(){
		imgScrollLeft2($('.case').find('.list'),$('.case').find('li').length-1,135,0);
		})	
	$('.case').find('li').each(function(i){
		$(this).click(function(){
			$('.case').find('li').removeClass('liNow');
			$(this).addClass('liNow');
			$('.case').find('.contentDiv').hide();
			$('.case').find('.contentDiv').eq(i).show();
			})
		})		
	//--下载
	var downNow=1000;
	$('.down').find('li').each(function(i){
	$(this).click(function(){
		if(downNow==i){
			$('.down').find('li').removeClass('liNow');
			downNow=1000;
			}else{
				downNow=i;
				$('.down').find('li').removeClass('liNow');
				$(this).addClass('liNow');
				}
		})	
	})	
	//--faq
	$('.help').find('li').each(function(i){
	$(this).find('.more').toggle(
	    function(){
			$('.help').find('li').eq(i).addClass('liNow');
			$(this).html('点击隐藏部分');
			},
		function(){
			$('.help').find('li').eq(i).removeClass('liNow');
			$(this).html('点击展开全部');
			}
	)
	})		
	//
	})